In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.offline as pyo
import plotly.graph_objs as go

In [2]:
df = pd.read_csv('the_simpsons')

In [3]:
df

,Season,Episode,Title,Year,Total votes,Average rating,z-score
0,1,1,Simpsons Roasting on an Open Fire,1989,"7,412.00",8.1,1.12
1,1,2,Bart the Genius,1990,"4,920.00",7.7,0.64
2,1,3,Homer's Odyssey,1990,"4,333.00",7.3,0.15
3,1,4,There's No Disgrace Like Home,1990,"4,270.00",7.7,0.64
4,1,5,Bart the General,1990,"4,600.00",7.9,0.88
...,...,...,...,...,...,...,...
722,33,18,My Octopus and a Teacher,2022,302.00,6.5,-0.82
723,33,19,Girls Just Shauna Have Fun,2022,276.00,6.6,-0.70
724,33,20,Marge the Meanie,2022,253.00,6.6,-0.70
725,33,21,Meat Is Murder,2022,274.00,5.7,-1.80
726,33,22,Poorhouse Rock,2022,416.00,5.4,-2.16

In [4]:
data_by_season = df.groupby(['Season'], as_index = False)['Average rating'].agg(['mean', 'median'])

In [5]:
data_by_season

            mean  median
Season
1       7.707692    7.70
2       8.009091    8.00
3       8.154167    8.20
4       8.272727    8.20
5       8.322727    8.30
6       8.344000    8.50
7       8.360000    8.40
8       8.216000    8.10
9       7.824000    7.90
10      7.600000    7.60
11      7.290909    7.30
12      7.323810    7.20
13      7.081818    7.10
14      7.036364    7.05
15      7.000000    7.10
16      6.980952    7.00
17      6.827273    6.80
18      6.922727    6.90
19      6.880000    6.80
20      6.885714    7.00
21      6.795652    6.80
22      6.722727    6.75
23      6.740909    6.85
24      6.718182    6.75
25      6.745455    6.65
26      6.604545    6.60
27      6.627273    6.55
28      6.428571    6.40
29      6.557143    6.50
30      6.147826    6.20
31      6.409091    6.50
32      6.354545    6.30
33      6.463636    6.50

In [26]:
fig = px.line(data_by_season,data_by_season.index,data_by_season['mean'], title= 'Mean avegare rating by season')
pyo.plot(fig, filename='avgseason.html')

'avgseason.html'

In [7]:
data_by_season_and_episode = df.groupby(['Season'], as_index = True)

In [8]:
data_by_season_and_episode.head()

,Season,Episode,Title,Year,Total votes,Average rating,z-score
0,1,1,Simpsons Roasting on an Open Fire,1989,"7,412.00",8.1,1.12
1,1,2,Bart the Genius,1990,"4,920.00",7.7,0.64
2,1,3,Homer's Odyssey,1990,"4,333.00",7.3,0.15
3,1,4,There's No Disgrace Like Home,1990,"4,270.00",7.7,0.64
4,1,5,Bart the General,1990,"4,600.00",7.9,0.88
...,...,...,...,...,...,...,...
705,33,1,The Star of the Backstage,2021,963.00,4.3,-3.50
706,33,2,Bart's in Jail!,2021,606.00,7.0,-0.22
707,33,3,Treehouse of Horror XXXII,2021,641.00,6.7,-0.58
708,33,4,The Wayz We Were,2021,507.00,6.8,-0.46
709,33,5,Lisa's Belly,2021,580.00,6.7,-0.58

In [9]:
season_1 = df.loc[df['Season'] == 1]
season_2 = df.loc[df['Season'] == 2]
season_3 = df.loc[df['Season'] == 3]
season_4 = df.loc[df['Season'] == 4]
season_5 = df.loc[df['Season'] == 5]
season_6 = df.loc[df['Season'] == 6]
season_7 = df.loc[df['Season'] == 7]
season_8 = df.loc[df['Season'] == 8]
season_9 = df.loc[df['Season'] == 9]
season_10 = df.loc[df['Season'] == 10]
season_11 = df.loc[df['Season'] == 11]
season_12 = df.loc[df['Season'] == 12]
season_13 = df.loc[df['Season'] == 13]
season_14 = df.loc[df['Season'] == 14]
season_15 = df.loc[df['Season'] == 15]
season_16 = df.loc[df['Season'] == 16]
season_17 = df.loc[df['Season'] == 17]
season_18 = df.loc[df['Season'] == 18]
season_19 = df.loc[df['Season'] == 19]
season_20 = df.loc[df['Season'] == 20]
season_21 = df.loc[df['Season'] == 21]
season_22 = df.loc[df['Season'] == 22]
season_23 = df.loc[df['Season'] == 23]
season_24 = df.loc[df['Season'] == 24]
season_25 = df.loc[df['Season'] == 25]
season_26 = df.loc[df['Season'] == 26]
season_27 = df.loc[df['Season'] == 27]
season_28 = df.loc[df['Season'] == 28]
season_29 = df.loc[df['Season'] == 29]
season_30 = df.loc[df['Season'] == 30]
season_31 = df.loc[df['Season'] == 31]
season_32 = df.loc[df['Season'] == 32]
season_33 = df.loc[df['Season'] == 33]

In [10]:
trace1 = go.Scatter(x=season_1['Episode'], y=season_1['Average rating'], mode ='lines', name ='Season 1')
trace2 = go.Scatter(x=season_2['Episode'], y=season_2['Average rating'], mode ='lines', name ='Season 2')
trace3 = go.Scatter(x=season_3['Episode'], y=season_3['Average rating'], mode ='lines', name ='Season 3')
trace4 = go.Scatter(x=season_4['Episode'], y=season_4['Average rating'], mode ='lines', name ='Season 4')
trace5 = go.Scatter(x=season_5['Episode'], y=season_5['Average rating'], mode ='lines', name ='Season 5')
trace6 = go.Scatter(x=season_6['Episode'], y=season_6['Average rating'], mode ='lines', name ='Season 6')
trace7 = go.Scatter(x=season_7['Episode'], y=season_7['Average rating'], mode ='lines', name ='Season 7')
trace8 = go.Scatter(x=season_8['Episode'], y=season_8['Average rating'], mode ='lines', name ='Season 8')
trace9 = go.Scatter(x=season_9['Episode'], y=season_9['Average rating'], mode ='lines', name ='Season 9')
trace10 = go.Scatter(x=season_10['Episode'], y=season_10['Average rating'], mode ='lines', name ='Season 10')
trace11 = go.Scatter(x=season_11['Episode'], y=season_11['Average rating'], mode ='lines', name ='Season 11')
trace12 = go.Scatter(x=season_12['Episode'], y=season_12['Average rating'], mode ='lines', name ='Season 12')
trace13 = go.Scatter(x=season_13['Episode'], y=season_13['Average rating'], mode ='lines', name ='Season 13')
trace14 = go.Scatter(x=season_14['Episode'], y=season_14['Average rating'], mode ='lines', name ='Season 14')
trace15 = go.Scatter(x=season_15['Episode'], y=season_15['Average rating'], mode ='lines', name ='Season 15')
trace16 = go.Scatter(x=season_16['Episode'], y=season_16['Average rating'], mode ='lines', name ='Season 16')
trace17 = go.Scatter(x=season_17['Episode'], y=season_17['Average rating'], mode ='lines', name ='Season 17')
trace18 = go.Scatter(x=season_18['Episode'], y=season_18['Average rating'], mode ='lines', name ='Season 18')
trace19 = go.Scatter(x=season_19['Episode'], y=season_19['Average rating'], mode ='lines', name ='Season 19')
trace20 = go.Scatter(x=season_20['Episode'], y=season_20['Average rating'], mode ='lines', name ='Season 20')
trace21 = go.Scatter(x=season_21['Episode'], y=season_21['Average rating'], mode ='lines', name ='Season 21')
trace22 = go.Scatter(x=season_22['Episode'], y=season_22['Average rating'], mode ='lines', name ='Season 22')
trace23 = go.Scatter(x=season_23['Episode'], y=season_23['Average rating'], mode ='lines', name ='Season 23')
trace24 = go.Scatter(x=season_24['Episode'], y=season_24['Average rating'], mode ='lines', name ='Season 24')
trace25 = go.Scatter(x=season_25['Episode'], y=season_25['Average rating'], mode ='lines', name ='Season 25')
trace26 = go.Scatter(x=season_26['Episode'], y=season_26['Average rating'], mode ='lines', name ='Season 26')
trace27 = go.Scatter(x=season_27['Episode'], y=season_27['Average rating'], mode ='lines', name ='Season 27')
trace28 = go.Scatter(x=season_28['Episode'], y=season_28['Average rating'], mode ='lines', name ='Season 28')
trace29 = go.Scatter(x=season_29['Episode'], y=season_29['Average rating'], mode ='lines', name ='Season 29')
trace30 = go.Scatter(x=season_30['Episode'], y=season_30['Average rating'], mode ='lines', name ='Season 30')
trace31 = go.Scatter(x=season_31['Episode'], y=season_31['Average rating'], mode ='lines', name ='Season 31')
trace32 = go.Scatter(x=season_32['Episode'], y=season_32['Average rating'], mode ='lines', name ='Season 32')
trace33 = go.Scatter(x=season_33['Episode'], y=season_33['Average rating'], mode ='lines', name ='Season 33')

In [21]:
data = [trace7, trace8, trace9]
#data = [trace1, trace2, trace3, trace4, trace5, trace6, trace7, trace8, trace9, trace10, trace11, trace12, trace13, trace14, trace15, trace16, trace17, trace18, trace19, trace20, trace21, trace22, trace23, trace24, trace25, trace26, trace27, trace28, trace29, trace30, trace31, trace32, trace33]

In [22]:
layout = go.Layout(title = 'Season')

In [23]:
figure = go.Figure(data=data, layout= layout)
pyo.plot(figure, filename='allseasons.html')

'allseasons.html'

In [14]:
df.loc[df['Season'] == 1]

,Season,Episode,Title,Year,Total votes,Average rating,z-score
0,1,1,Simpsons Roasting on an Open Fire,1989,"7,412.00",8.1,1.12
1,1,2,Bart the Genius,1990,"4,920.00",7.7,0.64
2,1,3,Homer's Odyssey,1990,"4,333.00",7.3,0.15
3,1,4,There's No Disgrace Like Home,1990,"4,270.00",7.7,0.64
4,1,5,Bart the General,1990,"4,600.00",7.9,0.88
5,1,6,Moaning Lisa,1990,"4,147.00",7.6,0.51
6,1,7,The Call of the Simpsons,1990,"4,008.00",7.8,0.76
7,1,8,The Telltale Head,1990,"3,858.00",7.6,0.51
8,1,9,Life on the Fast Lane,1990,"3,823.00",7.4,0.27
9,1,10,Homer's Night Out,1990,"3,706.00",7.3,0.15
10,1,11,The Crepes of Wrath,1990,"3,767.00",7.8,0.76
11,1,12,Krusty Gets Busted,1990,"4,151.00",8.3,1.37
12,1,13,Some Enchanted Evening,1990,"4,094.00",7.7,0.64

In [15]:
for i in range(33):
   season +_+str(i)= df.loc[df['Season'] == i]

SyntaxError: cannot assign to operator (Temp/ipykernel_55072/3446041856.py, line 2)

In [17]:
season_6

,Season,Episode,Title,Year,Total votes,Average rating,z-score
103,6,1,Bart of Darkness,1994,"3,274.00",8.7,1.85
104,6,2,Lisa's Rival,1994,"2,765.00",8.1,1.12
105,6,3,Another Simpsons Clip Show,1994,"2,439.00",5.8,-1.67
106,6,4,Itchy & Scratchy Land,1994,"3,108.00",8.6,1.73
107,6,5,Sideshow Bob Roberts,1994,"2,725.00",8.2,1.24
108,6,6,Treehouse of Horror V,1994,"4,335.00",9.2,2.46
109,6,7,Bart's Girlfriend,1994,"2,716.00",8.1,1.12
110,6,8,Lisa on Ice,1994,"2,972.00",8.6,1.73
111,6,9,Homer Badman,1994,"4,100.00",8.9,2.10
112,6,10,Grampa vs. Sexual Inadequacy,1994,"2,534.00",8.1,1.12
113,6,11,Fear of Flying,1994,"2,582.00",7.7,0.64
114,6,12,Homer the Great,1995,"3,801.00",9.0,2.22
115,6,13,And Maggie Makes Three,1995,"3,331.00",8.8,1.97
116,6,14,Bart's Comet,1995,"2,977.00",8.7,1.85
117,6,15,Homie the Clown,1995,"3,004.00",8.6,1.73
118,6,16,Bart vs. Australia,1995,"31,400.00",8.5,1.61
119,6,17,Homer vs. Patty and Selma,1995,"2,417.00",7.8,0.76
120,6,18,A Star Is Burns,1995,"2,947.00",8.5,1.61
121,6,19,Lisa's Wedding,1995,"2,825.00",8.3,1.37
122,6,20,Two Dozen and One Greyhounds,1995,"2,521.00",8.1,1.12
123,6,21,The PTA Disbands,1995,"2,471.00",8.0,1.00
124,6,22,Round Springfield,1995,"2,871.00",8.2,1.24
125,6,23,The Springfield Connection,1995,"2,510.00",8.2,1.24
126,6,24,Lemon of Troy,1995,"3,114.00",8.7,1.85
127,6,25,Who Shot Mr. Burns? Part One,1995,"3,988.00",9.2,2.46

In [24]:
season_9

,Season,Episode,Title,Year,Total votes,Average rating,z-score
178,9,1,The City of New York vs. Homer Simpson,1997,"4,410.00",9.0,2.22
179,9,2,The Principal and the Pauper,1997,"3,110.00",7.0,-0.22
180,9,3,Lisa's Sax,1997,"2,266.00",8.1,1.12
181,9,4,Treehouse of Horror VIII,1997,"2,457.00",8.2,1.24
182,9,5,The Cartridge Family,1997,"2,500.00",8.2,1.24
183,9,6,Bart Star,1997,"2,119.00",7.7,0.64
184,9,7,The Two Mrs. Nahasapeemapetilons,1997,"2,055.00",7.7,0.64
185,9,8,Lisa the Skeptic,1997,"2,264.00",8.1,1.12
186,9,9,Realty Bites,1997,"2,046.00",7.6,0.51
187,9,10,Miracle on Evergreen Terrace,1997,"2,259.00",7.6,0.51
188,9,11,"All Singing, All Dancing",1998,"2,378.00",5.0,-2.65
189,9,12,Bart Carny,1998,"2,143.00",7.7,0.64
190,9,13,The Joy of Sect,1998,"2,384.00",8.3,1.37
191,9,14,Das Bus,1998,"2,334.00",8.2,1.24
192,9,15,The Last Temptation of Krust,1998,"1,993.00",7.5,0.39
193,9,16,Dumbbell Indemnity,1998,"2,018.00",7.7,0.64
194,9,17,Lisa the Simpson,1998,"2,245.00",8.0,1.00
195,9,18,This Little Wiggy,1998,"2,108.00",7.9,0.88
196,9,19,Simpson Tide,1998,"2,599.00",8.1,1.12
197,9,20,The Trouble with Trillions,1998,"2,423.00",7.8,0.76
198,9,21,Girly Edition,1998,"2,055.00",7.8,0.76
199,9,22,Trash of the Titans,1998,"2,788.00",8.4,1.49
200,9,23,King of the Hill,1998,"2,490.00",8.2,1.24
201,9,24,Lost Our Lisa,1998,"1,980.00",7.7,0.64
202,9,25,Natural Born Kissers,1998,"2,132.00",8.1,1.12

In [25]:
season_8

,Season,Episode,Title,Year,Total votes,Average rating,z-score
153,8,1,Treehouse of Horror VII,1996,"2,904.00",8.4,1.49
154,8,2,You Only Move Twice,1996,"5,535.00",9.2,2.46
155,8,3,The Homer They Fall,1996,"2,526.00",8.1,1.12
156,8,4,"Burns, Baby Burns",1996,"2,464.00",7.7,0.64
157,8,5,Bart After Dark,1996,"2,592.00",8.3,1.37
158,8,6,A Milhouse Divided,1996,"2,443.00",8.1,1.12
159,8,7,Lisa's Date with Density,1996,"2,375.00",7.8,0.76
160,8,8,Hurricane Neddy,1996,"3,340.00",8.7,1.85
161,8,9,El Viaje Misterioso de Nuestro Jomer,1997,"3,314.00",8.6,1.73
162,8,10,The Springfield Files,1997,"4,066.00",9.0,2.22
163,8,11,The Twisted World of Marge Simpson,1997,"2,324.00",7.7,0.64
164,8,12,Mountain of Madness,1997,"3,064.00",8.5,1.61
165,8,13,Simpsoncalifragilisticexpiala(Annoyed Grunt)cious,1997,"2,602.00",7.7,0.64
166,8,14,The Itchy & Scratchy & Poochie Show,1997,"2,528.00",7.9,0.88
167,8,15,Homer's Phobia,1997,"3,814.00",8.8,1.97
168,8,16,Brother from Another Series,1997,"2,552.00",8.2,1.24
169,8,17,"My Sister, My Sitter",1997,"2,690.00",7.9,0.88
170,8,18,Homer vs. the 18th Amendment,1997,"3,106.00",8.8,1.97
171,8,19,Grade School Confidential,1997,"2,713.00",8.2,1.24
172,8,20,The Canine Mutiny,1997,"2,169.00",7.6,0.51
173,8,21,The Old Man and the Lisa,1997,"2,288.00",7.9,0.88
174,8,22,In Marge We Trust,1997,"2,371.00",8.1,1.12
175,8,23,Homer's Enemy,1997,"5,762.00",9.3,2.58
176,8,24,The Simpsons Spin-Off Showcase,1997,"2,287.00",7.1,-0.09
177,8,25,The Secret War of Lisa Simpson,1997,"2,256.00",7.8,0.76

In [27]:
git remote add origin https://github.com/YeisonABL/The_Simpson.git

SyntaxError: invalid syntax (Temp/ipykernel_55072/3116007240.py, line 1)